#!/usr/bin/expect -f
set timeout 30

spawn ssh -o StrictHostKeyChecking=no -o PubkeyAuthentication=no -o PreferredAuthentications=password -p 55535 rodrigo@178.156.234.198
expect "password:" { send "Esseanoemeu@2026\r" }
expect "$ "

set db_url "postgresql://laranjinha:laranjinha-npx-tech@localhost:5432/inside_sales_pipeline"

send "export PAGER=cat\r"
expect "$ "

send "psql \"$db_url\" -c \"\\dt\"\r"
expect "$ "

send "exit\r"
expect eof
